version: '3'

services:
  galaxy-db:
    image: postgres:16
    container_name: galaxy-db
    # убрать на продакшене
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./galaxy-db:/var/lib/postgresql/data
    restart: always