version: '3'

services:
  user-ms-db:
    image: postgres:16
    container_name: user-ms-db
    # убрать на продакшене
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./user-ms-db:/var/lib/postgresql/data
    restart: always

  product-ms-db:
    image: mongo
    container_name: product-ms-db
    # убрать на продакшене
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./product-ms-db:/data/db
    restart: always