version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

  user-ms-db:
    image: postgres:16
    container_name: user-ms-db
    # убрать на продакшене
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./user-ms-db:/var/lib/postgresql/data
    restart: unless-stopped

  product-ms-db:
    image: mongo
    container_name: product-ms-db
    # убрать на продакшене
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./product-ms-db:/data/db
    restart: unless-stopped

  review-ms-db:
    image: mysql
    container_name:  review-ms-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      # переименовать на review-ms-db
      - MYSQL_DATABASE=product-ms-db
    # убрать на продакшене
    ports:
      - 3306:3306
    volumes:
      - ./review-ms-db:/var/lib/mysql
    restart: unless-stopped

  shoppng-ms-db:
    image: mariadb
    container_name: shoppng-ms-db
    environment:
      - MARIADB_DATABASE=shoppng-ms-db
      - MARIADB_ROOT_PASSWORD=root
    # убрать на продакшене
    ports:
      - 3307:3306
    volumes:
      - ./shoppng-ms-db:/var/lib/mysql
    restart: unless-stopped